### PR TITLE
TSDEV-1699 - User authentication + code refactoring.

### PR DESCRIPTION
**Pull request by Coooi**
- Class to Function components
- Navigation bar + mobile
- Folder restructuring
- Components Refactoring
- Color palette
- Routing mechanism
- Sign in, Sign up, Sign out flows
- My Profile page
- Protected routes

### CODE REVIEW

**Comment by tommueller** [comment]
@Coooi the restructuring seems fine, however I cannot run the code, as there are import errors.
Seems to be originating from inconsistent naming, i.e. it cannot import `import Navbar from './components/Navbar/Navbar';` because the folder is not capitalized in the project.

**Comment by Coooi** [comment]
> @Coooi the restructuring seems fine, however I cannot run the code, as there are import errors. Seems to be originating from inconsistent naming, i.e. it cannot import `import Navbar from './components/Navbar/Navbar';` because the folder is not capitalized in the project.

I just pushed a fix. It seems git was ignoring case sensitivity.

**Comment by tommueller** [comment]
@Coooi Now I have all the files duplicated in `navbar` and `Navbar` folders etc.

**Comment by tommueller** [comment]
Other then that it's looking good (I just deleted the folders locally). I like the new navbar and style!

**Comment by Coooi** [comment]
@tommueller Cool right? I've just pushed some changes:
Added Routing;
Converted FAQ dialog into a page.
Restructured Home grid layout.

**Comment by tommueller** [comment]
@Coooi Nice.
I still have the issue that all component folders are now duplicated as navbar and Navbar i.e., other then that it's working well

**Comment by Coooi** [comment]
@tommueller try deleting the folder and cloning the project again.
I've added now the register and login endpoints.
Where should I place the value of a new env varaible? It's called `JWT_SECRET`. 
For now I've got it only on my .env file.

**Comment by Coooi** [comment]
@tommueller 
Hi Tom, 
I have now added the login and signup flows.
I'm going on vacation tomorrow, so if you have time, would you please merge and deploy it so Migan can showcase it to the team on sunshine (staging)?
Feel free to commit anything if needed.

**Pull request merged**
